# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog/"
weight = 2

[[main]]
name = "Community"
url = "/community/"
weight = 3

[[main]]
name = "GitHub ⭐️"
url = "https://github.com/microcks/microcks"
weight = 4

[[main]]
name = "Docs"
url = "/documentation"
weight = 5


## Documentation Menus

[[docs]]
  name = "Using"
  weight = 5
  identifier = "using"
  url = "using/"

[[docs]]
  name = "Installing"
  weight = 15
  identifier = "installing"
  url = "installing/"

[[docs]]
  name = "Automating"
  weight = 20
  identifier = "automating"
  url = "/automating"

[[docs]]
  name = "Administrating"
  weight = 21
  identifier = "administrating"
  url = "/administrating"

[[docs]]
  name = "Guides"
  weight = 22
  identifier = "guides"
  post = "break"
  url = "guides"

[[docs]]
  name = "Resources"
  weight = 25
  identifier = "resources"
  url = "/resources/"

[[docs]]
  name = "Community"
  weight = 30
  identifier = "community"
  url = "/community/"

# footer menu left
[[footer_left]]
name = "Quick Start"
url = "https://microcks.io/documentation/getting-started/"

# footer menu middle
[[footer_middle]]
name = "Privacy Policy"
url = "https://www.linuxfoundation.org/legal/privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "https://www.linuxfoundation.org/legal/terms"
